old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        add_tickets:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.add_tickets', type: direct}

    consumers:
        add_tickets:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.add_tickets', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.add_tickets'}
            callback: App\Consumer\Ticket\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
